spring.application.name:
    liquibase-demo
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: sa

#    jdbc:h2:mem:43228eb7-8ce4-4f23-abcd-6bfedafa9d6d

